GET http://localhost:3002/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "with user 222",
    "important": true,
    "userId": "6448ee9ba173ff76da7266b3"
}


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST client",
    "important": true
}

###
GET http://localhost:3001/api/notes/fakeurl

###
POST http://localhost:3001/api
Content-Type: application/json

{
}


###
DELETE http://localhost:3001/api/notes/64478b8b07334bf85a276ba1

###
PUT  http://localhost:3001/api/notes/64478ca04dd2ea923195037c
Content-Type: application/json

{
    "content": "VS Code REST client",
    "important": false
}